In [1]:
import numpy as np

#### arange : 0부터 지정한 숫자까지의 배열을 만들어줌

In [2]:
np.arange(30).reshape(-1,5)   # row 개수를 지정하지 않음(알아서 지정해주게)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [3]:
np.arange(0, 5, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [4]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### ones, zeros & empty

In [8]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [11]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [12]:
# 거의 사용 X
np.empty(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [13]:
np.empty((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)   # xxx_like(기존 array): 기존 array의 shape으로 ndarray 생성(ones_like, zeros_like, empty_likes)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### eye, identity & digonal

In [15]:
np.identity(n=3, dtype=np.int8)   # identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [16]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
np.eye(N=3, M=5, dtype=np.int8)   # 비대칭 단위행렬 생성가능

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [19]:
np.eye(3)   # = np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
np.eye(3, 5, k=2)   # k: 시작하는 column 지정

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)    # 대각원소 뽑아줌

array([0, 4, 8])

In [22]:
np.diag(matrix, k=1)

array([1, 5])

In [23]:
np.random.uniform(0,1,10).reshape(2,5)

array([[ 0.48886999,  0.16262246,  0.75753397,  0.33683281,  0.43311875],
       [ 0.24239608,  0.10323929,  0.38531444,  0.83152465,  0.25219176]])

In [24]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.27275952,  0.50944928, -0.97937319,  1.50028282, -0.84917367],
       [-1.41045734,  0.35572557, -1.1025633 ,  1.9208721 ,  1.474921  ]])