# Numpy Assignment

In [1]:
import numpy as np

#### n_size_ndarray_creation

- Template

```python
def n_size_ndarray_creation(n, dtype=np.int):
    X = None
    return X
```

- 함수목적
  - n의 제곱수로 2 dimentional array를 생성하는 ndarray.
- Args
  - n: 생성하고자 하는 ndarray의 row와 column의 개수
  - dtype: 생성하려는 ndarray의 data type (np.int)
- Returns
  - row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [5]:
def n_size_ndarray_creation(n, dtype=np.int):
    result = np.arange(n**2, dtype=dtype).reshape(n,n)
    return result

n_size_ndarray_creation(9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

#### zero_or_one_or_empty_ndarray

- Template

```python
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    X = None
  return X
```

- 함수목적
  - shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.
- Args
  - shape: 생성할려는 ndarray의 shape
  - type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨
  - dtype: 생성하려는 ndarray의 data type (np.int)
- Returns
  - shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨
- Examples

```python
>>> zero_or_one_or_empty_ndarray(shape=(2,2), type=1)
array([[ 1,  1],
        [ 1,  1]])
>>> zero_or_one_or_empty_ndarray(shape=(3,3), type=99)
#임의의수 생성
array([[1773984320,        487, 1774114944],
        [       487, 1947927088,          0],
        [1947927088,          0, 1701605485]])
```

In [50]:
# 내가 짠 코드
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        result = np.zeros(shape, dtype=dtype)
    elif type == 1:
        result = np.ones(shape, dtype=dtype)
    elif type == 99:
        result = np.empty(shape, dtype=dtype)
    return result

zero_or_one_or_empty_ndarray(shape=(2,2), type=1)

array([[1, 1],
       [1, 1]])

In [51]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

array([[-666058536,        413,          0],
       [         0,          0,          0],
       [         0,          0,          0]])

#### change_shape_of_ndarray

- Template

```python
def change_shape_of_ndarray(X, n_row):
    return X
```

- 함수목적
  - 입력된 ndarray X를 n_row의 값을 row의 개수로 지정한 matrix를 반환함.
  - 이때 입력하는 X의 size는 2의 거듭제곱수로 전제함.
  - 만약 n_row과 1일 때는 matrix가 아닌 vector로 반환함.
- Args
  - X: 입력하는 ndarray
  - n_row: 생성할려는 matrix의 row의 개수
- Returns
  - row의 개수가 n_row인 Matrix 또는 Vector
  - n_row가 1이면 Vector 값으로 반환함
- Examples

```python
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.ones((32,32), dtype=np.int)
>>> testcode.change_shape_of_ndarray(X, 1)
array([1, 1, 1, ..., 1, 1, 1])
>>> testcode.change_shape_of_ndarray(X, 512)
array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])
```

In [52]:
# 내가 짠 코드...이상
def change_shape_of_ndarray(X, n_row):
    result = X.reshape(n_row, -1)
    if n_row == 1:
        result = result[0]
    return result

array([1, 1, 1, ..., 1, 1, 1])

In [237]:
# 정답 코드
def change_shape_of_ndarray(X, n_row):
    result = X.flatten() if n_row == 1 else X.reshape(n_row, -1)   # flatten으로 1차원 vector로 변환
    return result

In [231]:
X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

In [232]:
change_shape_of_ndarray(X, 512)

array([[1, 1],
       [1, 1],
       [1, 1],
       ..., 
       [1, 1],
       [1, 1],
       [1, 1]])

#### concat_ndarray

- Template

```python
def concat_ndarray(X_1, X_2, axis):
    pass
```

- 함수목적
  - 입력된 ndarray X_1과 X_2를 axis로 입력된 축을 기준으로 통합하여 반환하는 함수
  - X_1과 X_2는 matrix 또는 vector 임, 그러므로 vector 일 경우도 처리할 수 가 있어야 함
  - axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨.
  - 단 X_1과 X_2 Matrix, Vector 형태로 들어왔다면, Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인할 것
- Args
  - X_1: 입력하는 ndarray
  - X_2: 입력하는 ndarray
  - axis: 통합의 기준이 되는 축 0 또는 1임
- Returns
  - X_1과 X_2과 통합된 matrix 타입의 ndarray
- Examples

```python
>>> import numpy as np
>>> import numpy_lab as testcode
>>> a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6]])
>>> testcode.concat_ndarray(a, b, 0)
array([[1, 2],
       [3, 4],
       [5, 6]])
>>> testcode.concat_ndarray(a, b, 1)
False
>>> a = np.array([1, 2])
>>> b = np.array([5, 6, 7])
>>> testcode.concat_ndarray(a, b, 1)
array([[1, 2, 5, 6, 7]])
>>> testcode.concat_ndarray(a, b, 0)
False
```

In [75]:
# 내가 짠 코드
def concat_ndarray(X_1, X_2, axis):
    if len(X_1.shape) == 1:
        X_1 = X_1.reshape(1,-1)
    if len(X_2.shape) == 1:
        X_2 = X_2.reshape(1,-1)
    if axis == 0:
        if X_1.shape[1] == X_2.shape[1]:
           result = np.concatenate((X_1, X_2), axis=axis)
        else:
            result = False
    elif axis == 1:
        if X_1.shape[0] == X_2.shape[0]:
           result = np.concatenate((X_1, X_2), axis=axis)
        else:
            result = False
    return result

In [238]:
# 정답 코드
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1,-1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1,-1)            
        return np.concatenate((X_1, X_2), axis=axis)
    except ValueError as e:
        return False

In [76]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
concat_ndarray(a, b, 1)

False

In [78]:
a = np.array([1, 2])
b = np.array([5, 6, 7])

concat_ndarray(a, b, 1)

array([[1, 2, 5, 6, 7]])

In [79]:
concat_ndarray(a, b, 0)

False

#### normalize_ndarray

- Template

```python
def normalize_ndarray(X, axis=99, dtype=np.float32):
    pass
```

- 함수목적
  - 입력된 Matrix 또는 Vector를 ndarray X의 정규화된 값으로 변환하여 반환함
  - 이때 정규화 변환 공식 `Z = (X - X의평균) / X의 표준편차`로 구성됨.
  - X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨.
  - Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함.
  - axis가 99일 경우 전체 값에 대한 normalize 값을 구함.
- Args
  - X: 입력하는 ndarray,
  - axis: normalize를 구하는 기준이 되는 축으로 0, 1 또는 99임, 단 99는 axis 구분 없이 전체값으로 평균과 표준편차를 구함
  - dtype: data type으로 np.float32로 구정
- Returns
  - 정규화된 ndarray
- Examples

```python
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.arange(12, dtype=np.float32).reshape(6,2)
>>> testcode.normalize_ndarray(X)
array([[-1.59325504, -1.3035723 ],
       [-1.01388955, -0.72420681],
       [-0.43452409, -0.14484136],
       [ 0.14484136,  0.43452409],
       [ 0.72420681,  1.01388955],
       [ 1.3035723 ,  1.59325504]], dtype=float32)
>>> testcode.normalize_ndarray(X, 1)
array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)
>>> testcode.normalize_ndarray(X, 0)
array([[-1.46385002, -1.46385002],
       [-0.87831002, -0.87831002],
       [-0.29277   , -0.29277   ],
       [ 0.29277   ,  0.29277   ],
       [ 0.87831002,  0.87831002],
       [ 1.46385002,  1.46385002]], dtype=float32)
```

In [128]:
# 내가 짠 코드
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 0:
        mean = np.mean(X, axis=axis, dtype=dtype)
        std = np.std(X, axis=axis, dtype=dtype)
    elif axis == 1:
        mean = np.mean(X, axis=axis, dtype=dtype).reshape(X.shape[0],-1)
        std = np.std(X, axis=axis, dtype=dtype).reshape(X.shape[0],-1)    
    elif axis == 99:
        mean = np.mean(X, dtype=dtype)
        std = np.std(X, dtype=dtype)
    result = (X - mean) / std
    return result

In [239]:
# 정답 코드
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column = X.shape
    elif axis == 99:
        mean = np.mean(X, dtype=dtype)
        std = np.std(X, dtype=dtype)
    if axis == 0:
        mean = np.mean(X, axis=axis, dtype=dtype)
        std = np.std(X, axis=axis, dtype=dtype)
    elif axis == 1:
        mean = np.mean(X, axis=axis, dtype=dtype).reshape(n_row,-1)
        std = np.std(X, axis=axis, dtype=dtype).reshape(n_row,-1)        
    Z = (X - mean) / std
    return Z

SyntaxError: invalid syntax (<ipython-input-239-de71a150a552>, line 5)

In [91]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
normalize_ndarray(X)

array([[-1.59325504, -1.3035723 ],
       [-1.01388955, -0.72420681],
       [-0.43452409, -0.14484136],
       [ 0.14484136,  0.43452409],
       [ 0.72420681,  1.01388955],
       [ 1.3035723 ,  1.59325504]], dtype=float32)

In [129]:
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [108]:
normalize_ndarray(X, 0)

array([[-1.46385002, -1.46385002],
       [-0.87831002, -0.87831002],
       [-0.29277   , -0.29277   ],
       [ 0.29277   ,  0.29277   ],
       [ 0.87831002,  0.87831002],
       [ 1.46385002,  1.46385002]], dtype=float32)

#### save_ndarray

- Template

```python
def save_ndarray(X, filename="test.npy"):
  pass
```

- 함수목적
  - 입력된 ndarray X를 argument filename으로 저장함
- Args
  - X: 입력하는 ndarray
  - filename: 저장할려는 파일이름
- Examples

```python
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.arange(32, dtype=np.float32).reshape(4, -1)
>>> filename = "test.npy"
>>> testcode.save_ndarray(X, filename) #test.npy 파일이 생성됨
```

In [131]:
# 내가 짠 코드
def save_ndarray(X, filename="test.npy"):
    np.savetxt(filename, X)

In [240]:
# 정답 코드
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename, "wb")
    np.savetxt(filename, X)

In [132]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(X, filename)   # test.npy 파일이 생성됨

#### boolean_index

- Template

```python
def boolean_index(X, condition):
  pass
```

- 함수목적
  - 입력된 ndarray X를 String type의 condition 정보를 바탕으로 해당 컨디션에 해당하는 ndarray X의 index 번호를 반환함
  - 단 이때, str type의 조건인 condition을 코드로 변환하기 위해서는 `eval(str("X") + condition)`를 사용할 수 있음
- Args
  - X: 입력하는 ndarray
  - condition: string type의 조건 (">3", "== 5", "< 15")
- Returns
  - 조건에 만족하는 ndarray X의 index
- Examples

```python
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.arange(32, dtype=np.float32).reshape(4, -1)
>>> testcode.boolean_index(X, "== 3")
(array([0]), array([3]))
>>> X = np.arange(32, dtype=np.float32)
>>> testcode.boolean_index(X, "> 6")
(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31]),)
```

In [202]:
# 내가 짠 코드 ...이상
def boolean_index(X, condition):
    result = np.where(eval(str("X") + condition))
    return result

In [241]:
# 정답 코드
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

In [203]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
boolean_index(X, "== 3")

(array([0], dtype=int64), array([3], dtype=int64))

In [204]:
X = np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

#### find_nearest_value

- Template

```python
def find_nearest_value(X, target_value):
    pass
```

- 함수목적
  - 입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함
  - 이때 X를 list로 변경하여 처리하는 것은 실패로 간주함.
- Args
  - X: 입력하는 vector type의 ndarray
  - target_value : 가장 유사한 값의 기준값이 되는 값
- Returns
  - target_value와 가장 유사한 값
- Examples

```python
>>> import numpy as np
>>> import numpy_lab as testcode
>>> X = np.random.uniform(0, 1, 100)
>>> target_value = 0.3
>>> testcode.find_nearest_value(X, target_value)
0.29260674329282488 # 출력되는 값은 random 하게 바뀜
```

In [233]:
# 내가 짠 코드
def find_nearest_value(X, target_value):
    result = X[np.argmin( abs(X - target_value) )]
    return result

In [242]:
# 정답 코드
def find_nearest_value(X, target_value):
    return X[np.argmin( np.abs(X - target_value) )]

In [214]:
X = np.random.uniform(0, 1, 100)
target_value = 0.3
find_nearest_value(X, target_value)   # 출력되는 값은 random하게 바뀜

0.98623529008842381

#### get_n_largest_values

- Template

```python
def get_n_largest_values(X, n):
    pass
```

- 함수목적
  - 입력된 vector type의 ndarray X에서 큰 숫자 순서대로 n개의 값을 반환함.
- Args
  - X: vector type의 ndarray
  - n: 반환할려는 element의 개수
- Returns
  - ndarray X의 element중 큰 숫자 순서대로 n개 값이 반환됨 ndarray
- Examples

```python
>>> import numpy as np
>>> import numpy_lab_solution as t
>>> X = np.random.uniform(0, 1, 100)
>>> t.get_n_largest_values(X, 3)
array([ 0.98935239,  0.98494578,  0.98317255])
>>> t.get_n_largest_values(X, 5)
array([ 0.98935239,  0.98494578,  0.98317255,  0.96859596,  0.96485649])
# 출력되는 값은 random 하게 바뀜
```

In [227]:
# 내가 짠 코드
def get_n_largest_values(X, n):
    X = np.sort(X)[::-1]
    result = X[:n]
    return result

In [234]:
# 정답 코드
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

In [235]:
X = np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)   # 출력되는 값은 random하게 바뀜

array([ 0.43681319,  0.72030877,  0.88486702])

In [236]:
get_n_largest_values(X, 5)   # 출력되는 값은 random하게 바뀜

array([ 0.43681319,  0.72030877,  0.88486702,  0.73058142,  0.55656019])