# Tensor Manipulation (Tensor 처리/조작)

In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # seed 지정

# pprint 모듈 : 출력 결과를 이쁘게(?) 만들어 주는 모듈(들여쓰기 등)
pp = pprint.PrettyPrinter(indent=4)
# tf.InteractiveSession() : Session을 만든다는 점에서 tf.Session과 비슷
# but tf.run()이 아닌 .eval()을 사용함!!!
# sess = tf.Session() 방법으로 Session을 지정했을 때는
# tf.run() 또는 객체명.eval(session=sess)
sess = tf.InteractiveSession()

## Simple Array (1차 array)

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 2가지 방법의 차이 확인!!
print(t)
pp.pprint(t)

print(t.ndim) # 1차원
print(t.shape) # 7 x 0
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

[ 0.  1.  2.  3.  4.  5.  6.]
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
pp.pprint(t)
print(t.ndim) # 2차원
print(t.shape) # 4 x 3

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]
array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Shape, Rank, Axis
> 앞에서 만든 Session 객체가 tf.InteractiveSession()이기 때문에
>
> tf.run()이 아닌 객체명.eval() 사용
- Shape : 형태가 어떤지? ex) 3x5  (== dim() in R)
- Rank : rank(위수) - 몇차원인지?
- Axis : 축 (가장 안에 있는 것이 0, 하나씩 밖으로 나오면서 1씩 증가)

In [8]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [9]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [12]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [11]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [22]:
matrix1 = tf.constant([[3., 1.]])
matrix2 = tf.constant([[2.],[1.]])
# (1 x 2) %*% (2 x 1)
tf.matmul(matrix1, matrix2).eval()

array([[ 7.]], dtype=float32)

In [23]:
(matrix1*matrix2).eval()  # 위치에 해당하는 것 끼리 각각 곱해버림

array([[ 6.,  2.],
       [ 3.,  1.]], dtype=float32)

## Watch out broadcasting
> broadcasting : tf가 알아서 형변환을 한 후에 계산하는 것

In [26]:
matrix1 = tf.constant([[3., 1.]])
matrix2 = tf.constant([[2.],[1.]])
# broadcasting이 일어남!
(matrix1 + matrix2).eval()

array([[ 5.,  3.],
       [ 4.,  2.]], dtype=float32)

In [25]:
matrix1 = tf.constant([[3., 1.]])
matrix2 = tf.constant([[2., 1.]])
# 같은 shape일 때는 정상적으로 계산
(matrix1 + matrix2).eval()

array([[ 5.,  2.]], dtype=float32)

## Random values for variable initializations 

In [2]:
tf.random_normal([3]).eval()

array([ 2.20866942, -0.73225045,  0.33533147], dtype=float32)

In [3]:
tf.random_uniform([2]).eval()

array([ 0.08186948,  0.42999184], dtype=float32)

In [4]:
tf.random_uniform([2, 3]).eval()

array([[ 0.43535876,  0.76933432,  0.65130949],
       [ 0.90863407,  0.06278825,  0.85073185]], dtype=float32)

## Reduce Mean/Sum
> 여기서 reduce의 의미 : 차원을 없앤다는 뜻
> 
> 즉, 현재 있는 차원을 없애고 그 내부의 값들로 mean or sum한다는 뜻

In [29]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [45]:
x = [[1., 2.],
     [3., 4.]]
# axis 옵션 없으면 모든 dimension reduce(차원 삭제)한 후 모든 값들의 mean을 구함
tf.reduce_mean(x).eval()

2.5

In [47]:
# axis=0 : 가장 바깥쪽 dimension reduce(열 기준 계산)
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [48]:
# axis=1 : 밖에서 2th dimension reduce(행 기준 계산)
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [53]:
# axis=-1 : 가장 안쪽에 있는 dimension reduce
# 여기의 예에서는 axis=1 과 같음
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [54]:
# 옵션 없으면 모든 값 axis 구분 없이 계산
tf.reduce_sum(x).eval()

10.0

In [55]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [56]:
tf.reduce_sum(x, axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [57]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [58]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis
> tf.argmax() : index를 반환!!!

In [64]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()  # max 값이 여러개인 경우에는 맨 처음 나온 값의 index 반환

array([1, 0, 0], dtype=int64)

In [65]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [66]:
tf.argmax(x, axis=-1).eval()  # axis=1 과 동일

array([2, 0], dtype=int64)

## Reshape, squeeze, expand_dims

In [69]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape  # 3차원 array

(2, 2, 3)

In [70]:
# shape 변환(n x 3의 형태로 변환)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
# n x 1 x 3 의 형태로 변환
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [72]:
# tf.squeeze() : 붎필요하게 묶여있는 차원(한 차원 안에 원소가 단 하나 뿐일 때)을 제거시켜주는 함수
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [73]:
# tf.expand_dims(data, num) : data를 num만큼 차원을 높여줌
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

## One hot
> 입력된 값의 index에는 1, 나머지는 0으로 채워주는 형태를 반환
>
> 자동으로 shape(차원) 하나 증가시킴
>
> depth보다 큰 index는 표현되지 않음

In [88]:
tf.one_hot([0, 1, 2, 0], depth=3).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [89]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [80]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()  # 증가된 차원을 reshape으로 낮춰줌

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## casting
> 값 형태 변경
>
> 조건문 사용 가능

In [91]:
# 값을 int로 변환(소수점 이하 버림)
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [93]:
# True면 '1', False면 '0'
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [98]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# 데이터를 합쳐줌 (default : axis=0)
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
# axis=1 (열 기준)으로 데이터를 합쳐줌
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like
- tf.ones_like() : 데이터를 모두 1로 채워줌
- tf.zeros_like() : 데이터를 모두 0으로 채워줌

In [99]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [100]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip
> 같은 index에 있는 값들끼리 묶어서 데이터 만들어줌

In [104]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [105]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [135]:
t = np.array([[1,2,3], [4,5,6]])
pp.pprint(t)

array([[1, 2, 3],
       [4, 5, 6]])


In [136]:
tf.transpose(t).eval() # transpose 해줌

array([[1, 4],
       [2, 5],
       [3, 6]])

In [138]:
tf.transpose(t, [1,0]).eval()  # default : [1,0]  # [0,1]은 원래 array와 동일

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [128]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [124]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [125]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [126]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
