# Lab 6 Softmax Classifier

## Lab06-1-softmax_classifier

In [1]:
import tensorflow as tf

In [2]:
tf.set_random_seed(777)  # seed 지정

In [3]:
# train data
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
X = tf.placeholder("float", [None, 4])  # n x 4 data
Y = tf.placeholder("float", [None, 3])  # n x 3 data (output이 3개!! => 세 값의 합은 항상 1)

In [5]:
nb_classes = 3  # class 개수(output의 category 개수)

In [6]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [7]:
# tf.nn.softmax() : softmax activation fn으로 logit을 0과 1 사이의 확률로 표현
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [8]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [9]:
# Optimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [10]:
# Session 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))     # tf.argmax(a, 1) : a를 행에서 가장 큰 값의 index 반환('0'은 열)

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

'''
--------------
[[  1.38904958e-03   9.98601854e-01   9.06129117e-06]] [1]
--------------
[[ 0.93119204  0.06290206  0.0059059 ]] [0]
--------------
[[  1.27327668e-08   3.34112905e-04   9.99665856e-01]] [2]
--------------
[[  1.38904958e-03   9.98601854e-01   9.06129117e-06]
 [  9.31192040e-01   6.29020557e-02   5.90589503e-03]
 [  1.27327668e-08   3.34112905e-04   9.99665856e-01]] [1 0 2]
'''

0 5.04862
200 0.548425
400 0.432149
600 0.352466
800 0.276829
1000 0.232683
1200 0.210553
1400 0.192215
1600 0.176752
1800 0.163534
2000 0.152108
--------------
[[  1.38904317e-03   9.98601973e-01   9.06124023e-06]] [1]
--------------
[[ 0.93119204  0.06290206  0.00590588]] [0]
--------------
[[  1.27327668e-08   3.34113225e-04   9.99665856e-01]] [2]
--------------
[[  1.38904317e-03   9.98601973e-01   9.06124023e-06]
 [  9.31192040e-01   6.29020557e-02   5.90588432e-03]
 [  1.27327668e-08   3.34113225e-04   9.99665856e-01]] [1 0 2]


'\n--------------\n[[  1.38904958e-03   9.98601854e-01   9.06129117e-06]] [1]\n--------------\n[[ 0.93119204  0.06290206  0.0059059 ]] [0]\n--------------\n[[  1.27327668e-08   3.34112905e-04   9.99665856e-01]] [2]\n--------------\n[[  1.38904958e-03   9.98601854e-01   9.06129117e-06]\n [  9.31192040e-01   6.29020557e-02   5.90589503e-03]\n [  1.27327668e-08   3.34112905e-04   9.99665856e-01]] [1 0 2]\n'