# Lab 7 Learning rate and Evaluation

## Lab07-3-linear_regression_min_max

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.set_random_seed(777)  # for reproducibility

In [3]:
# 각 변수별로 최대값=1, 최소값=0, 나머지 값들은 그 사이의 값으로 이루어지게 scale 변환하는 함수
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [4]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [5]:
# very important. It does not work without it.
# 앞에서 정의한 MinMaxScaler()로 scale 변환해줌(normalization)
xy = MinMaxScaler(xy)
print(xy)

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]


In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
# Hypothesis (using linear regression)
hypothesis = tf.matmul(X, W) + b

In [9]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
100 Cost:  0.152254
Prediction:
 [[ 1.63450289]
 [ 0.06628087]
 [ 0.35014752]
 [ 0.67070574]
 [ 0.61131608]
 [ 0.61466062]
 [ 0.23175186]
 [-0.13716528]]

'''


0 Cost:  0.152309 
Prediction:
 [[ 1.63461912]
 [ 0.06613699]
 [ 0.3500818 ]
 [ 0.67072517]
 [ 0.61130744]
 [ 0.61464405]
 [ 0.23171967]
 [-0.13728359]]
1 Cost:  0.152309 
Prediction:
 [[ 1.63461804]
 [ 0.06613836]
 [ 0.35008252]
 [ 0.67072499]
 [ 0.61130762]
 [ 0.61464429]
 [ 0.23171999]
 [-0.13728246]]
2 Cost:  0.152308 
Prediction:
 [[ 1.63461685]
 [ 0.06613982]
 [ 0.35008317]
 [ 0.67072475]
 [ 0.61130774]
 [ 0.61464441]
 [ 0.23172033]
 [-0.13728121]]
3 Cost:  0.152308 
Prediction:
 [[ 1.63461566]
 [ 0.06614128]
 [ 0.35008389]
 [ 0.67072463]
 [ 0.6113078 ]
 [ 0.61464453]
 [ 0.23172063]
 [-0.13728008]]
4 Cost:  0.152307 
Prediction:
 [[ 1.63461447]
 [ 0.06614277]
 [ 0.35008448]
 [ 0.67072445]
 [ 0.61130786]
 [ 0.61464471]
 [ 0.23172095]
 [-0.13727888]]
5 Cost:  0.152306 
Prediction:
 [[ 1.63461328]
 [ 0.0661442 ]
 [ 0.35008517]
 [ 0.67072421]
 [ 0.61130798]
 [ 0.61464489]
 [ 0.23172128]
 [-0.13727769]]
6 Cost:  0.152306 
Prediction:
 [[ 1.6346122 ]
 [ 0.06614557]
 [ 0.35008579]
 [ 0.

'\n100 Cost:  0.152254\nPrediction:\n [[ 1.63450289]\n [ 0.06628087]\n [ 0.35014752]\n [ 0.67070574]\n [ 0.61131608]\n [ 0.61466062]\n [ 0.23175186]\n [-0.13716528]]\n\n'