# Lab 4 Multi-variable linear regression

## Lab04-1-multi_variable_linear_regression
## Using matrix - 앞에서 한 것과 같은 결과

In [1]:
import tensorflow as tf

In [2]:
tf.set_random_seed(777)

In [3]:
# 5x3 matrix
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
# 5x1 vector(matrix)
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [4]:
# placeholder 변수 생성
X = tf.placeholder(tf.float32, shape=[None, 3])     # n x 3 matrix (None : 개수가 정해져있지 않다는 뜻; 데이터의 수)
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [5]:
# initial value 지정
W = tf.Variable(tf.random_normal([3, 1]), name='weight')    # weight 3개가 필요!! (3x1)
b = tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
# regression model
hypothesis = tf.matmul(X, W) + b    # tf.matmul(X, W) : 행렬곱(X %*% W) - matrix multiply

In [7]:
# cost/loss function (MSE) - matrix form
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Session 생성 및 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22656.0 
Prediction:
 [[ 22.04806328]
 [ 21.61978722]
 [ 24.09669304]
 [ 22.29300499]
 [ 18.6339016 ]]
10 Cost:  6.04175 
Prediction:
 [[ 155.17454529]
 [ 181.64263916]
 [ 181.76219177]
 [ 193.9883728 ]
 [ 140.69340515]]
20 Cost:  5.81316 
Prediction:
 [[ 155.56951904]
 [ 182.13209534]
 [ 182.23675537]
 [ 194.50674438]
 [ 141.0690918 ]]
30 Cost:  5.79204 
Prediction:
 [[ 155.56291199]
 [ 182.13885498]
 [ 182.23573303]
 [ 194.50717163]
 [ 141.07659912]]
40 Cost:  5.77101 
Prediction:
 [[ 155.55511475]
 [ 182.14413452]
 [ 182.23324585]
 [ 194.50604248]
 [ 141.08297729]]
50 Cost:  5.75011 
Prediction:
 [[ 155.54734802]
 [ 182.1493988 ]
 [ 182.23078918]
 [ 194.50492859]
 [ 141.08934021]]
60 Cost:  5.72934 
Prediction:
 [[ 155.5395813 ]
 [ 182.15461731]
 [ 182.228302  ]
 [ 194.50376892]
 [ 141.09565735]]
70 Cost:  5.70863 
Prediction:
 [[ 155.53186035]
 [ 182.15988159]
 [ 182.2258606 ]
 [ 194.50268555]
 [ 141.10197449]]
80 Cost:  5.68806 
Prediction:
 [[ 155.5241394 ]
 [ 182.165100